export const LOGIN_LOADING = 'LOGIN LOADING'
export const LOGIN_SUCCESS = 'LOGIN SUCCESS'
export const LOGIN_FAILURE = 'LOGIN FAILURE'

export const ITEM_DELIVERY_SUCCESS = 'ITEM DELIVERY SUCCESS'
export const CLEAR_SINGLE_ITEM = 'CLEAR SINGLE ITEM'
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE NOTIFICATION SUCCESS'
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE NOTIFICATION FAILURE'
export const UPDATE_NOTIFICATION_LOADING = 'UPDATE NOTIFICATION LOADING'

export const INVENTORY_LOADING = 'INVENTORY LOADING'
export const INVENTORY_SUCCESS = 'INVENTORY SUCCESS'
export const INVENTORY_FAILURE = 'INVENTORY FAILURE'
export const INVENTORY_UPDATE_ADD = 'INVENTORY UPDATE ADD'
export const INVENTORY_UPDATE_REMOVE = 'INVENTORY UPDATE REMOVE'

export const GET_SINGLE_ITEM_SUCCESS = 'GET SINGLE ITEM SUCCESS'
export const GET_SINGLE_ITEM_FAILURE = 'GET SINGLE ITEM FAILURE'

export const INVENTORY_RECIVER_ADD = 'INVENTORY RECIVER ADD'
export const INVENTORY_RECIVER_REMOVE = 'INVENTORY RECIVER REMOVE'

export const USERDATA_LOADING = 'USERDATA LOADING'
export const USERDATA_SUCCESS = 'USERDATA SUCCESS'
export const USERDATA_FAILURE = 'USERDATA FAILURE'


export const SIGNUP_LOADING = 'SIGNUP LOADING'
export const SIGNUP_SUCCESS = 'SIGNUP SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP FAILURE'

export const CHANGE_PASSWORD_LOADING = 'CHANGE PASSWORD LOADING'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE PASSWORD SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE PASSWORD FAILURE'

export const LOGOUT_LOADING = 'LOGOUT LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT FAILURE'


export const PROJECT_LOADING = 'PROJECT LOADING'
export const PROJECT_SUCCESS = 'PROJECT SUCCESS'
export const PROJECT_FAILURE = 'PROJECT FAILURE'

export const DASHBOARD_SUCCESS = 'DASHBOARD SUCCESS'
export const DASHBOARD_FAILURE = 'DASHBOARD FAILURE'

export const DONATE_SUCCESS = 'DONATE_SUCCESS'
export const DONATE_FAILURE = 'DONATE_FAILURE'

export const CATALOG_SUCCESS = 'CATALOG_SUCCESS'
export const CATALOG_FAILURE = 'CATALOG_FAILURE'

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'

export const ADD_DONATION_SUCCESS = 'ADD_DONATION_SUCCESS'
export const ADD_DONATION_FAILURE = 'ADD_DONATION_FAILURE'

export const INTEREST_SUCCESS = 'INTEREST_SUCCESS'
export const INTEREST_FAILURE = 'INTEREST_FAILURE'

export const DISINTEREST_SUCCESS = 'DISINTEREST_SUCCESS'
export const DISINTEREST_FAILURE = 'DISINTEREST_FAILURE'

export const CHAT_SUCCESS = 'CHAT_SUCCESS'
export const CHAT_FAILURE = 'CHAT_FAILURE'

export const SET_NOTIFICATION_SUCCESS = 'SET_NOTIFICATION_SUCCESS'
export const SET_NOTIFICATION_FAILURE = 'SET_NOTIFICATION_FAILURE'
